windowrule {
  name = workspace-ai
  match:class = ^(chrome-chatgpt\.com__-Default|chrome-claude\.ai__.*-Default)$
  workspace = 3
}

windowrule {
  name = workspace-chat
  match:class = ^(chrome-web\.telegram\.org__k_-Default|org\.telegram\.desktop|chrome-web\.whatsapp\.com__-Default|chrome-discord\.com__app-Default|chrome-discord\.com__channels_@me-Default|chrome-teams\.microsoft\.com__v2_-Default|com\.github\.IsmaelMartinez\.teams_for_linux)$
  workspace = 5
}

windowrule {
  name = float-helper
  match:class = ^(float-window)$

  float = on
  center = on
  size = 800 600
}

windowrule {
  name = snipaste-snipper
  match:class = ^(Snipaste)$
  match:title = ^(Snipper - Snipaste)$

  stay_focused = on
  pin = on
}

windowrule {
  name = snipaste-main
  match:class = ^(Snipaste)$
  match:title = ^(Snipaste)$

  stay_focused = on
  pin = on
}

windowrule {
  name = snipaste-paster
  match:class = ^(Snipaste)$
  match:title = ^(Paster - Snipaste)$

  pin = off
  stay_focused = off
}
