# Background and foreground colors
background = #000000
foreground = #ddd3de

# Standard colors
palette = 0=#000000
palette = 1=#b369bf
palette = 2=#c06acd
palette = 3=#c27acc
palette = 4=#bf57ce
palette = 5=#bd77c8
palette = 6=#ca84d4
palette = 7=#d0c7d1

# Bright colors
palette = 8=#b394b8
palette = 9=#d5a7dd
palette = 10=#dface7
palette = 11=#e2bae7
palette = 12=#d865e9
palette = 13=#d685e2
palette = 14=#e096eb
palette = 15=#ddd3de
