$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(189, 119, 200, 1)
$font_color = rgba(221, 211, 222, 1)
$placeholder_color = rgba(221, 211, 222, 0.7)
$check_color = rgba(202, 132, 212, 1)
