background            #000000
foreground            #ddd3de

# black
color0  #000000
color8  #b394b8

# red
color1  #b369bf
color9  #d5a7dd

# green
color2  #c06acd
color10 #dface7

# yellow
color3  #c27acc
color11 #e2bae7

# blue
color4  #bf57ce
color12 #d865e9

# magenta
color5  #bd77c8
color13 #d685e2

#cyan
color6  #ca84d4
color14 #e096eb

#white
color7  #d0c7d1
color15 #ddd3de


