
# ========= Border =========
file_panel_border = '#F9F9F9'
sidebar_border = '#F9F9F9'
footer_border = '#F9F9F9'

# ========= Border Active =========
file_panel_border_active = '#c4bebe'
sidebar_border_active = '#c4bebe'
footer_border_active = '#c4bebe'
modal_border_active = '#c4bebe'

# ========= Background (bg) =========
full_screen_bg = '#010101'
file_panel_bg = '#010101'
sidebar_bg = '#010101'
footer_bg = '#010101'
modal_bg = '#010101'

# ========= Foreground (fg) =========
full_screen_fg = '#ffffff'
file_panel_fg = '#ffffff'
sidebar_fg = '#ffffff'
footer_fg = '#ffffff'
modal_fg = '#ffffff'

# ========= Special Color =========
cursor = '#ffffff'
correct = '#a79e9e'
error = '#988e8e'
hint = '#e1dede'
cancel = '#988e8e'
gradient_color = ['#010101', "#bbb8b8"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#010101'
file_panel_top_path = '#bbb8b8'
file_panel_item_selected_fg = '#bbb8b8'
file_panel_item_selected_bg = '#010101'

# ========= Sidebar Special Items =========
sidebar_title = '#ffffff'
sidebar_item_selected_fg = '#bbb8b8'
sidebar_item_selected_bg = '#010101'
sidebar_divider = '#F9F9F9'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#988e8e'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#a79e9e'
